---
output:
  word_document: default
  html_document: default
---


## Import 

```{r, include = FALSE, warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE, message = FALSE,
  echo = F,
  comment = ""
)
#devtools::load_all(".")
library(ggplot2)
library(kableExtra)
library(knitr)
library(tibble)
library(iNEXT)
library(sets)
library(tidyr)
library(ade4)
library(tidyverse)
library(ape)
library(dplyr)
library(phytools)
library(miNEXT.beta)
library(magrittr)
library(chaoUtility)
library("future.apply")

Caguana <- read.table("F://Chao//Network diversity//shinyapp//heir.entropy//data/Caguana.txt")
Cialitos <- read.table("F://Chao//Network diversity//shinyapp//heir.entropy//data/Cialitos.txt")
Cordillera <- read.table("F://Chao//Network diversity//shinyapp//heir.entropy//data/Cordillera.txt")
Fronton <- read.table("F://Chao//Network diversity//shinyapp//heir.entropy//data/Fronton.txt")
data <- list(Cordillera = Cordillera,Caguana = Caguana,Fronton = Fronton,Cialitos = Cialitos)

rowtree <- read.newick("F://Chao//Network diversity//shinyapp//heir.entropy//tree/rowtree.txt")
coltree <- read.newick("F://Chao//Network diversity//shinyapp//heir.entropy//tree/coltree.txt")

puerto.rico = list()
puerto.rico[["data"]] = data
puerto.rico[["col.tree"]] = coltree
puerto.rico[["row.tree"]] = rowtree
# usethis::use_data(puerto.rico, overwrite = T)
```

```{r}
library(miNEXT.beta)
source('..//R//iNEXTlink.R')
source('..//R//myfunc.R')
source('..//R//subfunction.R')
```

```{r}
treat1 = read.csv("data\\beetles_treatA.csv")%>%tibble::column_to_rownames("X")
treat2 = read.csv("data\\beetles_treatB.csv")%>%tibble::column_to_rownames("X")
# tr1 = (treat1/10)%>%apply(2,function(x){ceiling(x)})%>%as.data.frame()
# tr2 = (treat2/10)%>%apply(2,function(x){ceiling(x)})%>%as.data.frame()
beetles <- list(G = treat1, O = treat2)
load(file = "data//beetles_tree.rda")
beetles_tree = tr

network_list = beetles
coltree = beetles_tree
rowtree = NULL
# rowtree = beetles_tree
```

```{r}
## remove species in data that not in tree
# match(c(1,3,5,7,8), c(3,7,8,1))
network_list = lapply(network_list, function(data){
  not_in = is.na(match(colnames(data), beetles_tree$tip.label))
  data[,!not_in]
})

#combined_div = ready4beta(network_list)
#sum(combined_div$abundance1 > 0 & combined_div$abundance2 > 0) / 4326
```


### Datainfo

```{r}
sample1 <- iNEXT.link(x = network_list, diversity = 'TD', datatype = "abundance", nboot = 10)
```

```{r}
kable(sample1$TDInfo)%>%
  kable_styling()
```

### Visualization

```{r}
bipartite::visweb(network_list[[1]]%>%as.matrix())
bipartite::visweb(network_list[[2]]%>%as.matrix())
```

## Taxonomic:
### Calculation

```{r, message = F, warning=F}
asy1 = Asy.link(network_list, diversity = 'TD', q = seq(0,2,0.25),nboot = 10)
obs1 = Obs.link(network_list, diversity = 'TD', q = seq(0,2,0.25),nboot = 10)
sc1 <- SC.link(x = network_list, datatype = "abundance", nboot = 10)
spec1 = Spec.link(network_list, q = seq(0,2,1), datatype = "abundance", nboot =10)



dissimilarity1 = iNEXT_beta.link(x = network_list, coverage_expected = seq(0.5,1,0.05),
                                 data_type='abundance',
                                 q = c(0, 1, 2),diversity='TD',
                                 nboot = 0, conf = 0.95, max_alpha_coverage=F, by='coverage')
```

### 1.Sample completeness

```{r, fig.height=3, fig.width=5}
ggSC.link(sc1)
```

### 2.Asymptotic/ Empirical diversity

```{r fig.height=3, fig.width=5}
ggAsy.link(rbind(obs1, asy1))
```

### 3.Rarefaction / Extrapolation

```{r, fig.width=7, fig.height=4, fig.align="center",warning=FALSE}
ggiNEXT.link(sample1, diversity = 'TD', type = 1,facet.var = "Order.q" )
ggiNEXT.link(sample1, diversity = 'TD', type = 3,facet.var = "Order.q" )
```

```{r}
# tabview = sample1$TDiNextEst$coverage_based
# tabview%>%arrange(goalSC, Order.q)
# 
# ggplot(tabview, aes(x = goalSC, y = qD, color = Assemblage))+
#   geom_line()+
#   facet_wrap(Order.q~.)
```


### 4.Specialization


```{r,fig.width=7, fig.height=4, fig.align="center",warning=FALSE}
ggSpec.link(spec1)
```
### 5. Dissimilarity

```{r,fig.width=7, fig.height=4, fig.align="center",warning=FALSE}
ggiNEXT_beta.link(dissimilarity1, type = 'B')
ggiNEXT_beta.link(dissimilarity1, type = 'D')
```

```{r}
kable(head(dissimilarity1$Region_1$gamma, 10))
kable(head(dissimilarity1$Region_1$alpha, 10))
kable(head(dissimilarity1$Region_1$beta, 10))
```


## Phylogenetic: 
### Calculation

```{r, message = F, warning=F}
# sample2 <- iNEXT.link(x = network_list, diversity = 'PD', datatype = "abundance", nboot = 10,col.tree = coltree, row.tree = rowtree)

asy2 = Asy.link(network_list, diversity = 'PD', q = seq(0,2,0.25),nboot = 10, 
                col.tree = coltree, row.tree = rowtree)
obs2 = Obs.link(network_list, diversity = 'PD', q = seq(0,2,0.25),nboot = 10,
                col.tree = coltree, row.tree = rowtree)
# sc1 <- SC.link(x = network_list, datatype = "abundance", nboot = 10)
spec2 = Spec.link(network_list, q = seq(0,2,1), datatype = "abundance", nboot =10)
# x = network_list; coverage_expected = seq(0.5,1,0.05);
#                                  data_type='abundance';
#                                  q = c(0, 1, 2);diversity='TD';
#                                  nboot = 0; conf = 0.95; max_alpha_coverage=F; by='coverage';
# col.tree = coltree; row.tree = rowtree
dissimilarity2 = iNEXT_beta.link(x = network_list, coverage_expected = seq(0.5,1,0.05),
                                 data_type='abundance',
                                 q = c(0, 1, 2),diversity='PD',
                                 nboot = 0, conf = 0.95, max_alpha_coverage=F, by='coverage',col.tree = coltree, row.tree = rowtree)
```

### 1.Sample completeness

```{r, fig.height=3, fig.width=5}
ggSC.link(sc1)+theme(legend.position = 'bottom')
```

### 2.Asymptotic/ Empirical diversity

```{r}
ggAsy.link(rbind(obs2, asy2))
```

### 3.Rarefaction / Extrapolation

```{r, fig.width=7, fig.height=4, fig.align="center",warning=FALSE}
ggiNEXT.link(sample2, diversity = 'PD', type = 1,facet.var = "Order.q" )
ggiNEXT.link(sample2, diversity = 'PD', type = 3,facet.var = "Order.q" )
```

### 4.Specialization


```{r, fig.width=7, fig.height=4, fig.align="center",warning=FALSE}
ggSpec.link(spec2)
```
### 5. Dissimilarity

```{r, fig.width=7, fig.height=4, fig.align="center",warning=FALSE}
ggiNEXT_beta.link(dissimilarity2, diversity = 'PD', type = 'B')
ggiNEXT_beta.link(dissimilarity2, diversity = 'PD', type = 'D')
```

